### PR TITLE
Fix string escaping with run-shell

### PR DESCRIPTION
**Pull request by noboruma**
Previous escaping was not working under debian 9 & 10 with tmux 2.8.
Escaping of the double quotes made run-shell complaining (and not running). I am proposing to avoid the escaping entirely by using the single quote alternative.

### CODE REVIEW

**Comment by roosta** [comment]
I can't get your pull request to work on latest Arch and tmux version 2.8, the pop.sh scripts exits with 126 whenever it is run, not entirely sure why.

**Comment by noboruma** [comment]
I had the same error, I had to `chmod u+x` on pop.sh to make it actually work. I will check if it is a commonly done like this in other tmux plugins, if it is, I will update my PR!

**Comment by roosta** [comment]
Got it to work when setting the execute flag. I'm not opposed to setting that permission permanently if it fixes issues on debian.

**Comment by noboruma** [comment]
Nice! Good to hear, I will update the PR with the new flag set.

**Comment by roosta** [comment]
Thanks for the pull request and your interest. Glad we got this bug sorted.

**Comment by noboruma** [comment]
Thank you for accepting my PR and for sharing that brilliant plugin!

**Pull request merged**
